services:
    dmzx.totalpms.listener:
        class: dmzx\totalpms\event\listener
        arguments:
            - @template
            - @user
            - @dbal.conn
        tags:
            - { name: event.listener }
